# Site settings
title: Ranok's Programming Notebook
email: jacob@jacobtorrey.com
description: > # this means to ignore newlines until "baseurl:"
    This is a place where I can capture challenges I've faced and methods to overcome them. 
    I hope you can find something of use to save time I've already wasted.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ranok.github.io" # the base hostname & protocol for your site
#twitter_username: jacobtorrey
github_username:  ranok

# Build settings
markdown: kramdown
